#pragma once

/* Enable the HAL modules your application uses. */
#define HAL_MODULE_ENABLED
#define HAL_CORTEX_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
#define HAL_FLASH_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_PWR_MODULE_ENABLED
#define HAL_RCC_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED
/* Add more as needed: HAL_SPI_MODULE_ENABLED, HAL_I2C_MODULE_ENABLED, ... */

#define HSE_VALUE    8000000U
#define HSI_VALUE   16000000U
#define LSI_VALUE      32000U
#define LSE_VALUE      32768U

#define VDD_VALUE               3300U
#define TICK_INT_PRIORITY       0U
#define USE_RTOS                0U
#define PREFETCH_ENABLE         1U
#define USE_HAL_ADC_REGISTER_CALLBACKS   0U
#define USE_HAL_CEC_REGISTER_CALLBACKS   0U
#define USE_HAL_COMP_REGISTER_CALLBACKS  0U
#define USE_HAL_DAC_REGISTER_CALLBACKS   0U
#define USE_HAL_I2C_REGISTER_CALLBACKS   0U
#define USE_HAL_I2S_REGISTER_CALLBACKS   0U
#define USE_HAL_IRDA_REGISTER_CALLBACKS  0U
#define USE_HAL_LPTIM_REGISTER_CALLBACKS 0U
#define USE_HAL_RNG_REGISTER_CALLBACKS   0U
#define USE_HAL_RTC_REGISTER_CALLBACKS   0U
#define USE_HAL_SMARTCARD_REGISTER_CALLBACKS 0U
#define USE_HAL_SMBUS_REGISTER_CALLBACKS 0U
#define USE_HAL_SPI_REGISTER_CALLBACKS   0U
#define USE_HAL_TIM_REGISTER_CALLBACKS   0U
#define USE_HAL_UART_REGISTER_CALLBACKS  0U
#define USE_HAL_USART_REGISTER_CALLBACKS 0U
#define USE_HAL_WWDG_REGISTER_CALLBACKS  0U

#include "stm32g0xx_hal_def.h"
